log_level: "debug"
http_server:
  address: ":8081"
  timeout: "2s"
jwt:
  issuer: auth-service
  access_expires_in: 5m
  refresh_expires_in: 24h
  public_key: jwtRS256.key.pub   
  private_key: jwtRS256.key
